name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Build simple binary
        run: go build
      - name: Package DEB
        run: ./package-deb.sh
      - name: Install gcc-multilib
        run: sudo apt-get install -y gcc-multilib
      - name: Build multiplatform binary
        run: |
          wget https://raw.githubusercontent.com/ohanome/go-multibuilder/main/build.php
          php build.php 1.0.0 # TODO: get version
      - name: Create Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: kulana
          path: |
            ./kulana
            ./kulana.deb
            ./dist/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build

      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: kulana
          path: ./kulana

  build-deb-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: ./package-deb.sh

      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: kulana
          path: ./kulana.deb

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build

      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: kulana
          path: ./kulana.exe
